{% set version = "2024-03-01" %}
{% set dotted_version = version.replace("-", ".") %}
{% set list = "ls -lathr" %}    # [unix]
{% set list = "dir /s" %}  # [win]
{% set prefix_env = "$PREFIX" %}    # [unix]
{% set prefix_env = "%PREFIX%" %}  # [win]


package:
  name: vale-spelling-aoo-mozilla-en-dict-split
  version: {{ version.replace("-", ".") }}

source:
  url: https://github.com/marcoagpinto/aoo-mozilla-en-dict/archive/{{ version }}gb.tar.gz
  sha256: 7a40044991daaa2bb8f26927f049f4205e54da665b71b73f85233a94ac24c515

build:
  number: 1
  noarch: generic
  merge_build_host: False
  ignore_run_exports:
    - python
    - python_abi

requirements:
  build:
    - python >=3.6
  host: []

outputs:
  - name: vale-spelling-aoo-mozilla-en-dict
    build: &build
      noarch: generic
    requirements:
      run:
        - vale
        - {{ pin_subpackage("vale-spelling-aoo-mozilla-en-dict-au", exact=True) }}
        - {{ pin_subpackage("vale-spelling-aoo-mozilla-en-dict-ca", exact=True) }}
        - {{ pin_subpackage("vale-spelling-aoo-mozilla-en-dict-gb", exact=True) }}
        - {{ pin_subpackage("vale-spelling-aoo-mozilla-en-dict-us", exact=True) }}
        - {{ pin_subpackage("vale-spelling-aoo-mozilla-en-dict-za", exact=True) }}
    test:
      files:
        - test_spelling.py
      requires:
        - pytest
        - python >=3.6
        - vale
      commands:
        - python test_spelling.py

  - name: vale-spelling-aoo-mozilla-en-dict-au
    build: *build
    script: &script write_rule.py
    requirements:
      run:
        - aoo-mozilla-en-dict-au {{ dotted_version }}.*
      run_constrained: &constrained
        - vale >=3.0
    test:
      commands:
        - cd {{ prefix_env }} && cd share/vale/styles/aoo-mozilla-en-dict-au && {{ list }} || exit 1
    about:
      license: MIT
      license_file: en_AU (Kevin Atkinson)/README_en_AU.txt

  - name: vale-spelling-aoo-mozilla-en-dict-ca
    build: *build
    script: *script
    requirements:
      run:
        - aoo-mozilla-en-dict-ca {{ dotted_version }}.*
      run_constrained: *constrained
    test:
      commands:
        - cd {{ prefix_env }} && cd share/vale/styles/aoo-mozilla-en-dict-ca && {{ list }} || exit 1
    about:
      license: MIT
      license_file: en_CA (Kevin Atkinson)/README_en_CA.txt

  - name: vale-spelling-aoo-mozilla-en-dict-gb
    build: *build
    script: *script
    requirements:
      run:
        - aoo-mozilla-en-dict-gb {{ dotted_version }}.*
      run_constrained: *constrained
    test:
      commands:
        - cd {{ prefix_env }} && cd share/vale/styles/aoo-mozilla-en-dict-gb && {{ list }} || exit 1
    about:
      license: LGPL-3.0-or-later
      license_file: en_GB (Marco Pinto)/README_en_GB.txt

  - name: vale-spelling-aoo-mozilla-en-dict-us
    build: *build
    script: *script
    requirements:
      run:
        - aoo-mozilla-en-dict-us {{ dotted_version }}.*
      run_constrained: *constrained
    test:
      commands:
        - cd {{ prefix_env }} && cd share/vale/styles/aoo-mozilla-en-dict-us && {{ list }} || exit 1
    about:
      license: MIT
      license_file: en_US (Kevin Atkinson)/README_en_US.txt

  - name: vale-spelling-aoo-mozilla-en-dict-za
    build: *build
    script: *script
    requirements:
      run:
        - aoo-mozilla-en-dict-za {{ dotted_version }}.*
      run_constrained: *constrained
    test:
      commands:
        - cd {{ prefix_env }} && cd share/vale/styles/aoo-mozilla-en-dict-za && {{ list }} || exit 1
    about:
      license: LGPL-3.0-or-later
      license_file: en_ZA (Dwayne Bailey)/README_en_ZA.txt

about:
  home: https://github.com/marcoagpinto/aoo-mozilla-en-dict
  summary: 'Vale-compatible English Dictionaries Project (AOO+Mozilla+others)'
  license: LGPL-3.0-or-later
  license_file: README.md

extra:
  feedstock-name: vale-spelling-aoo-mozilla-en-dict
  recipe-maintainers:
    - bollwyvl
